export const Menu = [
  {
    id: 1,
    image: "images/pizza.jpg",
    name: "pizza",
    category: "dinner",
    price: "290💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    link: "https://www.dominos.co.in/",
  },
  {
    id: 2,
    image: "images/southindian.jpg ",
    name: "South Indian",
    category: "dinner",

    price: "380💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    link: "http://www.sankalponline.com/",
  },
  {
    id: 3,
    image: "images/idaly.webp",
    name: "Idaly Sambhar",
    category: "breakfast",
    price: "30💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    link: "https://www.jassideparathe.com/",
  },
  {
    id: 4,
    image: "images/gujarati.jpg",
    name: "Gujarati Thali",
    category: "lunch",
    price: "480💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    link: "https://www.isconthal.com/",
  },
  {
    id: 5,
    image: "images/punjabi.jpg",
    name: "Punjabi Thali",
    category: "lunch",
    price: "300💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    link: "https://www.jassideparathe.com/",
  },
  {
    id: 6,
    image: "images/pauva.jpg",
    name: "Bateka-Pauva",
    category: "breakfast",
    price: "60💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    link: "https://www.jassideparathe.com/",
  },
  {
    id: 7,
    image: "images/chinese.jpg",
    name: "Chinese",
    category: "evening",
    price: "150💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    link: "https://www.chinesewokexpress.com/",
  },
  {
    id: 8,
    image: "images/bhajipav.jpg",
    name: "Bhaji-Paw",
    category: "evening",
    price: "80💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    link: "https://kavish-caterarce-tiffine-service.business.site/",
  },
  {
    id: 9,
    image: "images/icecreme.png",
    name: "Ice-Creame",
    category: "evening",
    price: "50💲",
    decription: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    link: "https://www.jassideparathe.com/",
  },
];
